### ISSUE TITLE
Add support for openType SVG color fonts

### ISSUE THREAD

**Issue by Mottie** [opentypejs/opentype.js#193]
It looks like [Microsoft is adopting the openType SVG color fonts](https://lists.w3.org/Archives/Public/public-svgopentype/2016Mar/0014.html) format, so adding support for the SVG `colr` and `cpal` objects would be necessary.

I was trying to see if I could figure it out myself, but I am just now learning how to process `ArrayBuffer` objects and `DataViews`. That combined with figuring out an unfamiliar code base would take me a long time. I won't stop trying to learn, and I'll still work on adding this feature in my free time, unless someone beats me to it.

Useful links:
- [W3C Spec](https://www.w3.org/2013/10/SVG_in_OpenType/).
- [`SVG`](https://www.microsoft.com/typography/otspec/svg.htm) table details (since it doesn't appear to be included in this library).
- SVG [`COLR`](https://www.microsoft.com/typography/otspec/colr.htm) (color) table details.
- SVG [`CPAL`](https://www.microsoft.com/typography/otspec/cpal.htm) (color palette) table details.
- Color Gecko Emoji [ttf](http://people.mozilla.org/~jkew/opentype-svg/GeckoEmoji.ttf) or [woff](http://people.mozilla.org/~jkew/opentype-svg/GeckoEmoji.woff) for testing ([demo](http://people.mozilla.org/~jkew/opentype-svg/GeckoEmoji.html)).
- [Awesome examples](https://hacks.mozilla.org/2014/10/svg-colors-in-opentype-fonts/).

**Comment by mqudsi** [comment]
I believe this is required for opentype.js to support emoji fonts.

**Comment by Jolg42** [comment]
@mqudsi Yes but actually it depends on the platform as Google's emojis are in `CBDT` `CBLC` tables, Microsoft's `COLR` `CPAL`, Apple's `sbix`

**Comment by talltyler** [comment]
Supporting a single standard is a whole lot better than not supporting any of them. 
As a first step I would suggest having the forEachGlyph function to return information about what character it can't render allowing things like emojis to be handled as exceptions in user code rather than returning glyph 0.

**Comment by Jolg42** [comment]
@talltyler the problem you're describing needs to be fixed, check the issue https://github.com/nodebox/opentype.js/issues/168 for more info

**Comment by talltyler** [comment]
I've addressed first issue in #297. The next issue has a few parts. We can only render vector paths. Color also isn't currently managed within the core code. If we are supporting bitmap fonts we should maybe talk about what other things we want to support. Also should we talk about how fallbacks fonts should work. After looking at these different table types, personally I don't like sbix as much as the other two. But adopting full SVG support has a few issues https://connect.microsoft.com/IE/feedback/details/809823/draw-svg-image-on-canvas-context but I also wonder what kind of browser support this library is trying to hit? If we don't think SVG is going to fly sticking with one of the bitmap focused formats might be best.

**Comment by JanisE** [comment]
Is this the issue why I get a "Error: Font doesn't contain TrueType or CFF outlines" message when uploading "Noto Color Emoji" font (google.com/get/noto/#emoji-zsye-color)?

**Comment by mqudsi** [comment]
@talltyler I somehow missed your comment, and you raise some very good questions. Font rendering was never easy, but now it's become a whole new level of complicated. But I think the goal behind the adoption of SVG and not a new vector/path markup language is to enable developers in need of rendering glyphs and symbols like this to make use of already existing, battle-tested libraries instead of needing to reinvent the wheel. I'd argue that the creators of the OpenType standard would probably be aghast to discover people thought it meant they had to write their own SVG parser and animation library to support these new features. 😉

**Comment by yisibl** [comment]
COLR/CPAL +1

**Comment by Connum** [comment]
As far as I can see, merging #490 should have closed this issue, right? Any objections?

**Comment by ILOVEPIE** [comment]
SVG fonts are not the same as color fonts. The SVG table is mac specific, we should support it and the other methods of rendering emoji.

**Comment by ILOVEPIE** [comment]
Microsoft is not adopting the SVG table btw, only apple.

**Comment by Connum** [comment]
SVG and COLR/CPAL are both now supported.
