### ISSUE TITLE
Support for variable font format tables

### ISSUE THREAD

**Issue by BaGsn** [opentypejs/opentype.js#233]
Have you planned to upgrade the library to support new opentype variation tables?

**Comment by Jolg42** [comment]
Hi @BaGsn 

So having support for OpenType 1.8 with font variations would be great, right now there is nobody working on it but it looks like some people are interested by this feature.

So as OpenType.js is an open-source project you can directly contribute to it or sponsor a contributor that can do it for you 😉

**Comment by devongovett** [comment]
[fontkit](https://github.com/devongovett/fontkit) supports variation fonts (the truetype version so far, not CFF2). Currently just reading is supported, not writing. Code is [here](https://github.com/devongovett/fontkit/blob/master/src/glyph/GlyphVariationProcessor.js).

**Comment by Jolg42** [comment]
@devongovett Nice!
But I missed something... The new OpenType 1.8 is the CFF2 version? What is the TrueType version? If you have a link to a spec/doc to help me understand the difference here it would be perfect! :)

**Comment by moyogo** [comment]
@Jolg42 the TrueType glyf table didn’t really change in OpenType 1.8 (the only minor changes is some clarification of 3 flags).

**Comment by Jolg42** [comment]
Ok 👍

**Comment by brawer** [comment]
The next step in OpenType.js would likely be to implement the [gvar](https://www.microsoft.com/typography/otspec/gvar.htm) table. For testing, try parsing [TestGVAROne](https://github.com/icu-project/text-rendering-tests/raw/master/fonts/TestGVAROne.ttf), [TestGVARTwo](https://github.com/icu-project/text-rendering-tests/raw/master/fonts/TestGVARTwo.ttf), and [TestGVARThree](https://github.com/icu-project/text-rendering-tests/raw/master/fonts/TestGVARThree.ttf) from Unicode’s [text rendering test suite](https://github.com/icu-project/text-rendering-tests). Maybe you’ll also find the [‘gvar’ codec in fonttools](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_v_a_r.py) and its [tests](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_v_a_r_test.py) useful when implementing this.

**Comment by fdb** [comment]
I'm very interested on working on this in the coming weeks, as I will be doing a workshop around variable fonts in Vilnius in December.

@brawer thanks for the pointers to the test suite -- will look into that.
@devongovett thanks for a link to the code!

**Comment by brawer** [comment]
@fdb, very cool and good luck! The OpenType 1.8 spec has a [Font Variations Overview](https://www.microsoft.com/typography/otspec/otvaroverview.htm) which I’d recommend reading as an intro.

**Comment by tshinnic** [comment]
In addition to Adobe's minimal offering of examples for Font Variations, 
* [AdobeVFPrototype.otf  and  AdobeVFPrototype.ttf](https://github.com/adobe-fonts/adobe-variable-font-prototype/releases), 

I just now found the efforts of Type Network Inc. with two fonts 
* [AmstelvarAlpha-VF.ttf](https://github.com/TypeNetwork/fb-Amstelvar/tree/master/fonts)  and  [Decovar-VF.ttf](https://github.com/TypeNetwork/fb-Decovar/tree/master/fonts)

The first Adobe font has CFF2 versus the second having glyf/gvar, **but** both are missing the `STAT`and `MVAR` tables. (see [current-limitations](https://github.com/adobe-fonts/adobe-variable-font-prototype/blob/master/README.md#current-limitations))

The TypeNetwork files *do* have tables such as `STAT` and presumably are more or less self-consistent, though since the tools aren't all ready yet they've had to take workarounds to generate the font files.

Here's the `ttx -l` listing of Decovar-VF.ttf

    Listing table info for "Decovar-VF.ttf":
        tag     checksum   length   offset
        ----  ----------  -------  -------
        DSIG  0x5557558B       40   264340
        GDEF  0x0610006F     1512    50496
        GPOS  0xAFFBBECD       90    52008
        HVAR  0xB472ED23     2121    52100
        OS/2  0x6D8E8668       96      408
      * STAT  0xB2921842      138    54224
        cmap  0x20C65265      494      976
        fvar  0xD0B4C150     1404    54364
        glyf  0x380D9A98    45772     1712
        gvar  0x476B8119   208570    55768
        head  0x113F253D       54      284
        hhea  0x0F6809E1       36      340
        hmtx  0x888D371E      472      504
        loca  0xB9108E50      238     1472
        maxp  0x02B70790       32      376
        name  0x42270885     2064    47484
        post  0x0533BC8C      947    49548

I started looking harder for things like `STAT` when I found that even fonttools had had to hardcode a sample table in binary just to have something to test against!

Oooo, at least one of the [unicode-org/text-rendering-tests](https://github.com/unicode-org/text-rendering-tests) test fonts, [Selawik-variable.ttf](https://github.com/unicode-org/text-rendering-tests/tree/master/fonts), has `STAT`and `avar` and `cvar` and more!  Other files too!

    HVAR  AdobeVFPrototype-Subset.otf   Selawik-variable.ttf    
          TestHVAROne.otf               TestHVARTwo.ttf         TestGVARFour.ttf
    STAT  Selawik-variable.ttf          TestGVAREight.ttf            
    avar  Selawik-variable.ttf          TestAVAR.ttf                 
    cvar  Selawik-variable.ttf          
    fvar  AdobeVFPrototype-Subset.otf   Selawik-variable.ttf    Zycon.ttf               
          TestAVAR.ttf                  TestGVAROne.ttf         TestGVARTwo.ttf
          TestGVARThree.ttf             TestGVARFour.ttf        TestGVAREight.ttf
          TestGVARNine.ttf              TestHVAROne.otf         TestHVARTwo.ttf              
    gvar  Selawik-variable.ttf          Zycon.ttf               TestAVAR.ttf            
          TestGVAROne.ttf               TestGVARTwo.ttf         TestGVARThree.ttf
          TestGVARFour.ttf              TestGVAREight.ttf       TestGVARNine.ttf        
          TestHVARTwo.ttf

Gee, a couple months more and maybe the OSes will support these...

**Comment by Connum** [comment]
Reading and rendering of the missing variation tables has been implemented via #699, writing will follow via #701. Closing.
