### ISSUE TITLE
Glyph copy constructor

### ISSUE THREAD

**Issue by Pomax** [opentypejs/opentype.js#59]
It would be very useful if there was a Glyph copy constructor, or factory method, so that modifications to a glyph can be made to copies, rather than the original (thus allowing things like modifying the same letter in a string with multiple instances in different ways).

The new Glyph constructor looks pretty good, but it might be useful to add an `if(options.points) { /* this is a copy constructor call */ }` so that copies are easily constructed

**Comment by Connum** [comment]
`Glyph.points` is actually just stored once during parsing of TrueType fonts, but it's not used again when calling `Glyph.path`, 
as that path is generated during parsing as well. But actually, now that variable fonts are implemented, those points are used for building the transformed path for TrueType fonts. `Glyph.points` and `Glyph.path` currenly have to be modified separately, which is something we need to remedy in the future. When setting the path, points shold be recalculated, and vice versa.

To answer your original question: There's currently no built-in way to duplicate a glyph. You need to do something like this:
```js
new Glyph(Object.assign({}, glyph, {points: deepCloneOfPoints, path: deepCloneOfPath}));
```

`[...glyph.points]` and `[...glyph.path]` will not be enough, because they still hold references to the objects, in those arrays, you'll actually need a deep copy either by using a package made for that, or the quick-and-dirty `JSON.parse(JSON.stringify(glyph.path))`
