### ISSUE TITLE
Is it possible to get the middle skeleton path of glyphs

### ISSUE THREAD

**Issue by rvnath** [opentypejs/opentype.js#71]
The font.getPath() method is giving me a path consisting of inner and outer boundaries of glyphs. I want to be able to find a skeletal path that goes through the middle of the glyph path.  See the red line in the below attached image.
![skeleton](https://cloud.githubusercontent.com/assets/4309494/4734576/9416a84c-59d5-11e4-93f8-50811e1cd9c0.PNG)

Currently, I am following a circuitous approach:
- going through each glyph's path, 
- finding out the indexes of relevant points on the outer border
- compute the middle points on them and connect them with a line.

For example, from the above fig., to draw a vertical line skeleton for the left leg of "M", I take the middle of points (1,11) and (12,13) and then draw a line through the computed middle points.

This approach is tedious and not scalable. This is also inaccurate, if I use a different font (because the point numbers are different).

Is there a generic way, in which I can draw a middle line skeleton, that can draw straight line based glyphs as well as curved ones?

I considered using ctx.scale() and ctx.translate() to scale down the outer border path to create what looks like a middle skeleton.  But, this seems to be not so accurate in case of curved paths, and especially if the font size changes.

Any clues how to approach this?

**Comment by seltzlab** [comment]
@rvnath I'd be interested too to find a solution to this problem. Did you found something good at the end?

**Comment by rvnath** [comment]
Hello seltziab,

Our business use case was may too much complex.  
=> The use case was to develop electronic signboards billing site, where we determine the no. of LED glow bulbs within a set of letters.
=> we had to draw not just one middle path. but many paths would come within a letter's glyph depending upon the stroke width of the glyph.
=> Stroke width of even a single glyph varies at different points.
=> As a consequence, the no. of inner skeletal lines within a letter varies from portion to portion.

So, our approach was semi-automatic and semi-manual:
-- Keeping in mind all these complexities, we let the artist determine which and how mnany skeletal lines come in which part of the letter
-- these lines are drawn using Adobe photoshop / Inkscape
-- Our program takes these paths as SVG and renders them in our website.

Now this worked for us and we are happy :)

**Comment by lgcc** [comment]
Wonder if anyone has a idea of this. I heard that Adobe's new project *Faces* for iPad can do such thing, yet it's not released

**Comment by fdb** [comment]
Sorry, this is outside of the scope of OpenType.js. We will give you the glyph outlines as they exist in the font: you'll probably want to use an additional library for this. (Although I have no idea if there is a JS library that does this?)

**Comment by lmgonzalves** [comment]
Any solution so far? I'm interested too.

**Comment by Jolg42** [comment]
Hi @lmgonzalves 
You can look what Prototypo is doing -> https://www.prototypo.io/ & Metapolator too http://metapolator.com/home/ both projects are open source!

**Comment by MCTaylor17** [comment]
Sorry for reviving this but I found a good resource regarding [single line fonts](http://imajeenyus.com/computer/20150110_single_line_fonts/index.shtml).  Maybe useful to somebody now or in the future.

**Comment by shubham4286** [comment]
is  there any library to get middle skeleton path ( in JS ) ??

**Comment by axkibe** [comment]
You guys are mixing things up.

TrueType and OpenType fonts store the outlines, they don't know a middle path and for a general case there might be none (just think of outline doing a triangle shape for exmpale). So in anyway this bejond the scope of opentype.js.

Single line fonts, are designed as single line to be stroked (that is a shape is moved along the line (like a pen) and the result is the font..  for cases you need the single line / stroking mechanism it surely is better to start with a font that has already been designed this way. 

And then there is this situation of you got a font already as truetype and instead of recreating a font all by yourself, you want to find a middle path, as good a possilbe. Supposing it has been designed in a way that gives a feasible solution (like the original post). Don't know if there is a ready made solution for this, I have done something similar in the past but otherway around as finding an outline, but contrary to standard stroking I wanted the edges to be cornered again. What I did was moving the individual path parts (being bezier curves at worst, lines in an ideal case) find their intersections and taking this as new path, so I would go some similar way to find something mostly in the middle. BTW: unfornutally the outline of one bezier is not one bezier again but in the general case can only be approximated by a series of. 

But anyway, while this one of the things one can use opentype.js as basis for,  because you'd need to know the font path.. it's not task of the library itself to be the solution at the same time for all possible applications.
